# Generated by Django 4.2.2 on 2023-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
