# Generated by Django 4.2.2 on 2023-07-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_booking_delete_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
    ]
