# Generated by Django 4.2.2 on 2023-07-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_capacity_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='position',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
