# Generated by Django 4.2.2 on 2023-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sapid',
            field=models.CharField(default='00000000', max_length=9, unique=True),
        ),
    ]
