# Generated by Django 4.2.2 on 2023-07-05 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_sapid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomno',
            new_name='room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='booked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='capacity',
        ),
    ]
