# Generated by Django 4.2.2 on 2023-07-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjectname',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
