# Generated by Django 4.2.2 on 2023-07-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_timeslot'),
    ]

    operations = [
    ]
