# Generated by Django 4.2.2 on 2023-07-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230715_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_hour',
            field=models.IntegerField(choices=[(8, '8 AM'), (9, '9 AM'), (10, '10 AM'), (11, '11 AM'), (12, '12 PM'), (13, '1 PM'), (14, '2 PM'), (15, '3 PM'), (16, '4 PM'), (17, '5 PM')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.room'),
        ),
    ]
