# Generated by Django 4.2.2 on 2023-07-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_room_remove_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
