# Generated by Django 4.2.2 on 2023-07-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='roomno',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.room'),
            preserve_default=False,
        ),
    ]
