# Generated by Django 4.2.2 on 2023-07-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_subject_course_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='roomno',
            new_name='name',
        ),
    ]
