# Generated by Django 4.2.2 on 2023-07-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_roomno_subjects_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('weekday', 'start_hour', 'room')},
        ),
    ]
