# Generated by Django 4.2.2 on 2023-07-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sapid',
            field=models.CharField(default='00000000', max_length=9, unique=True),
        ),
    ]
