# Generated by Django 4.2.2 on 2023-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_student_sapid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='subject',
            new_name='subjects',
        ),
    ]
