# Generated by Django 4.2.2 on 2023-07-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_subject_timeslot_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(blank=True, max_length=9, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.timeslot')),
            ],
            options={
                'unique_together': {('student', 'timeslot')},
            },
        ),
    ]
