# Generated by Django 4.2.2 on 2023-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_timeslot_is_booked_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start_hour',
            field=models.IntegerField(choices=[(8, '8'), (9, '9 AM'), (10, '10 AM'), (11, '11 AM'), (12, '12 PM'), (13, '1 PM'), (14, '2 PM'), (15, '3 PM'), (16, '4 PM'), (17, '5 PM')]),
        ),
    ]
