# Generated by Django 4.1 on 2023-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_timeslot_booked_seats_alter_timeslot_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
    ]
