# Generated by Django 4.2.4 on 2023-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
