# Generated by Django 4.2.4 on 2023-08-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_subjects_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='subjects',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.subjects'),
        ),
    ]
